version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile_jenkins
    container_name: jenkins_service
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    networks:
      - microservices_network
    privileged: true

networks:
  microservices_network:
    external: true

volumes:
  jenkins_home: