FROM php:8.2-apache

RUN apt-get update && apt-get install -y unzip libzip-dev zip && docker-php-ext-install pdo pdo_mysql zip && apt-get clean

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . /var/www/html

WORKDIR /var/www/html

RUN chown -R www-data:www-data /var/www/html

RUN composer install --no-interaction --prefer-dist --optimize-autoloader


RUN a2enmod rewrite

RUN sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf

RUN echo '<Directory /var/www/html/public>\n    AllowOverride All\n</Directory>' >> /etc/apache2/sites-available/000-default.conf

RUN mkdir -p storage/logs bootstrap/cache && chmod -R 775 storage bootstrap/cache

EXPOSE 8000
