version: '3.9'

services:
  gateway:
    container_name: gateway_service
    build:
      context: ./Gateway
      dockerfile: ../Dockerfile_gateway
    ports:
      - "8000:80"
    volumes:
      - ./Gateway:/var/www/html
    environment:
      - APP_ENV=testing
      - DB_HOST=mysql
      - DB_DATABASE=proyecto
      - DB_USERNAME=user
      - DB_PASSWORD=userpassword
      - X_API_KEY=1234
      - API_KEY=1234
      - MICROSERVICIO_FLASK=http://sistema:5000
    depends_on:
      - mysql
    networks:
      - microservices_network

  notificaciones:
    container_name: notificaciones_service
    build:
      context: ./notificaciones
      dockerfile: ../Dockerfile_gateway
    ports:
      - "8001:80"
    volumes:
      - ./notificaciones:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=proyecto
      - DB_USERNAME=user
      - DB_PASSWORD=userpassword
    depends_on:
      - mysql
    networks:
      - microservices_network

  sistema:
    container_name: sistema_service
    build:
      context: ./sistema
      dockerfile: Dockerfile_flask
    ports:
      - "5000:5000"
    volumes:
      - ./sistema:/app
    environment:
      - NOTIFICACIONES_URL=http://notificaciones:8001/api/send-sms
      - API_KEY=1234
    depends_on:
      - mysql
    networks:
      - microservices_network

  mysql:
    container_name: mysql_service
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices_network

networks:
  microservices_network:

volumes:
  mysql_data: