FROM jenkins/jenkins:lts

USER root

RUN mkdir -p /usr/local/lib/docker/cli-plugins


# Instalar Docker y Docker Compose v2
# Instalar Docker CLI y docker-compose
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    usermod -aG docker jenkins
    
RUN apt-get update && \
    apt-get install -y docker.io curl && \
    mkdir -p /usr/local/lib/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
    -o /usr/local/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose && \
    usermod -aG docker jenkins

USER jenkins


