# Usa la imagen base de Jenkins
FROM jenkins/jenkins:lts

# Cambia a root para instalar dependencias
USER root

# Instala Docker y Docker Compose
RUN apt-get update && \
    apt-get install -y docker.io curl && \
    curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    usermod -aG docker jenkins

# Vuelve al usuario jenkins
USER jenkins